({
	// 分别压缩不合并
	/* appDir:"./app/",
	baseUrl:"./app/",
	dir:"./app/build",
	fileExclusionRegExp: "/^\./app/",
	modules:[{name:"./app/scripts/main"}] */
	

	// 压缩合并到一个js文件中
    baseUrl:"./app/scripts",
	name:"./main",
	paths: {	
        'angular': '../../bower_components/angular/angular.min',
        'angular-route': '../../bower_components/angular-route/angular-route',
		// 'appAll':'./app/scripts/appAll',
        'angular-ui-tree': '../../bower_components/angular-ui-tree/dist/angular-ui-tree',
        'angular-ui-bootstrap': '../../bower_components/angular-bootstrap/ui-bootstrap-tpls.min',
        'angular-ui-grid': '../../bower_components/angular-ui-grid/ui-grid',
        'defineService':'./lib/defineService',
		'controllers/index'   		 		    :    './controllers/index',    		 		        
        'controllers/grabParamManage'             :    './controllers/grabParamManage',                   
        'controllers/addParamType'                 :    './controllers/addParamType',                     
        'controllers/detailParam'                :    './controllers/detailParam',                      
        'controllers/addParamRegex'                :    './controllers/addParamRegex',                    
        'controllers/modifyParamRegex'             :    './controllers/modifyParamRegex',                 
        'controllers/grabAppClassify'             :    './controllers/grabAppClassify',                  
        'controllers/grabBehaviorManage'           :    './controllers/grabBehaviorManage',               
        'controllers/addBehavior'                 :    './controllers/addBehavior',                      
        'controllers/grabWaitApp'                 :    './controllers/grabWaitApp',                      
        'controllers/grabWaitAppIos'               :    './controllers/grabWaitAppIos',                   
        'controllers/grabWaitAppPc'                :    './controllers/grabWaitAppPc',                    
        'controllers/grabWaitAppMobile'            :    './controllers/grabWaitAppMobile',                
        'controllers/modifyWaitApp'              :    './controllers/modifyWaitApp',                    
        'controllers/modifyPriority'              :    './controllers/modifyPriority',                   
        'controllers/addApp'                      :    './controllers/addApp',                           
        'controllers/addWebsite'                   :    './controllers/addWebsite',                       
        'controllers/addAppClassify'              :    './controllers/addAppClassify',                   
        'controllers/modifyAppClassify'         :    './controllers/modifyAppClassify',                
        'controllers/downloadApp'                 :    './controllers/downloadApp',                      
        'controllers/translate'                   :    './controllers/translate',                        
        'controllers/grabAleadyApp'                :    './controllers/grabAleadyApp',                    
        'controllers/modifyAleadyApp'             :    './controllers/modifyAleadyApp',                  
        'controllers/detailAleadyApp'             :    './controllers/detailAleadyApp',                  
        'controllers/modifyAleadyAppDomation'     :    './controllers/modifyAleadyAppDomation',          
        'controllers/addAleadyAppDomation'         :    './controllers/addAleadyAppDomation',             
        'controllers/detailAleadyAppDomation'      :    './controllers/detailAleadyAppDomation',          
        'controllers/addDetailAleadyAPP'          :    './controllers/addDetailAleadyAPP',               
        'controllers/countInfoParam'              :    './controllers/countInfoParam',                   
        'controllers/detailcountInfoParam'         :    './controllers/detailcountInfoParam',               
        'controllers/countInfoAppClassify'        :    './controllers/countInfoAppClassify',             
        'controllers/countInfoGrabBehavior'       :    './controllers/countInfoGrabBehavior',            
        'controllers/detailcountInfoGrabBehavior'  :    './controllers/detailcountInfoGrabBehavior',          
        'controllers/countInfoAppSource'           :    './controllers/countInfoAppSource',               
        'controllers/countInfoUserNumber'          :    './controllers/countInfoUserNumber',              
        'controllers/countInfoWechat'              :    './controllers/countInfoWechat',                  
        'controllers/modifydetailAleadyApp'		:	 './controllers/modifydetailAleadyApp',			
      
        'daterangepicker': '../../bower_components/daterangepicker/daterangepicker',
        'boot': '../../bower_components/bootstrap/dist/js/bootstrap',
        'moduleMenu':'./lib/moduleMenu',
        'definedropdown':'./lib/definedropdown',
        'xcConfirm': '../../bower_components/xcConfirm/js/xcConfirm',
        'qrcode':'./lib/qrcode',
        'validation':'./lib/validation',
        'angularFileUpload': '../../bower_components/file-upload/angular-file-upload',
        'jqueryUiJqLoding': './lib/jquery-ui-jqLoding',
        'countinfo':'./lib/countinfo',
        'domReady': '../../bower_components/requirejs-domReady/domReady',
        'moment': '../../bower_components/daterangepicker/moment',
        'jquery': '../../bower_components/jquery/dist/jquery.min',      
		'inputdropdown':'./lib/inputdropdown',
	    'remberHistory':'./lib/remberHistory',
    },
    shim: {
        'angular': {exports: 'angular'},
        'angular-route': {deps: ['angular'], exports: 'ngRoute'},
        'angular-ui-tree': {deps: ['angular']},
        'angular-ui-bootstrap': {deps: ['angular']},
        'angular-ui-grid': {deps: ['angular']},
        'jquery': {exports: 'jquery'},
        'daterangepicker': {deps: ['jquery','moment']},
        'angularFileUpload': {deps: ['angular'], exports: 'angularFileUpload'},
        'jqueryUiJqLoding': {deps: ['jquery'],exports: 'jqueryUiJqLoding'},
        'alert': {deps: ['jquery'],exports: 'alert'},
        'boot':{deps:['jquery'],exports:'boot'},
        'menuDisplay': {deps:['angular','angular-ui-tree'],exports:'menuDisplay'},
        'scrollArea':{deps:['angular','angular-ui-tree'],exports:'scrollArea'},

        'defineService':{deps:['angular','angular-ui-grid','jquery'],exports:'defineService'},
        'moduleMenu':{deps:['angular','angular-ui-tree']},
        'definedropdown':{deps:['angular'],exports:'definedropdown'},
        'xcConfirm': {deps: ['jquery'],exports: 'xcConfirm'},
        'qrcode': {deps: ['jquery'],exports: 'qrcode'},
        'validation':{deps:['angular','jquery']},
        'countinfo':{deps:['angular','angular-ui-grid']},
        'inputdropdown':{deps:['angular','jquery'],exports:'inputdropdown'},
        'remberHistory':{deps:['angular'],exports:'remberHistory'},
    },
	optimize:"none",
	findNestedDependencies: true,
    out: "./app/scripts/main-build.js", 
	
})